openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/sauce/{id}:
    get:
      tags:
        - sauce-controller
      operationId: get_1
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Sauce'
    put:
      tags:
        - sauce-controller
      operationId: update
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SauceDto'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Sauce'
  /api/topping:
    get:
      tags:
        - topping-controller
      operationId: index
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topping'
    post:
      tags:
        - topping-controller
      operationId: post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToppingDto'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Topping'
  /api/sauce:
    get:
      tags:
        - sauce-controller
      operationId: index_1
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sauce'
    post:
      tags:
        - sauce-controller
      operationId: post_1
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SauceDto'
          application/json:
            schema:
              $ref: '#/components/schemas/SauceDto'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Sauce'
  /api/pizza:
    get:
      tags:
        - pizza-controller
      operationId: index_2
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizza'
    post:
      tags:
        - pizza-controller
      operationId: post_2
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PizzaDto'
          application/json:
            schema:
              $ref: '#/components/schemas/PizzaDto'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Pizza'
  /api/topping/{id}:
    get:
      tags:
        - topping-controller
      operationId: get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Topping'
components:
  schemas:
    SauceDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    Sauce:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    ToppingDto:
      type: object
      properties:
        name:
          type: string
    Topping:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    PizzaDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        sauce:
          type: integer
          format: int32
        toppings:
          type: array
          items:
            type: integer
            format: int32
    Pizza:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        sauce:
          $ref: '#/components/schemas/Sauce'
        toppings:
          type: array
          items:
            $ref: '#/components/schemas/Topping'
